name: Back Create .env file

on:
  push:
    branches: [main]

jobs:
  job1:
    runs-on: linux-latest
    steps:
      - run: |
          touch .env
          echo "OPENAI_API_KEY=${{ secrets.API_ENV.OPENAI_API_KEY }}" >> .env
          echo "UPBIT_ACCESS_KEY=${{ secrets.API_ENV.UPBIT_ACCESS_KEY }}" >> .env
          echo "UPBIT_SECRET_KEY=${{ secrets.API_ENV.UPBIT_SECRET_KEY }}" >> .env
